name: laurencemanchee
favicon: null
layout_spectrum: 0.6516029005870223
typography_spectrum: 0.8455821676179767
title: Laurence Manchee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1e1e1e'
    - '#6b6863'
    - '#c8c8c6'
    - '#8fbd7c'
  brandStrength: 0.48429353232495487
  lightness: 0.5471973686944693
  saturation: 0.03720656712539494
  rhythmicContrast: 0.9251280247699469
purpose: []
